title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://kareemlsd.github.io/computationaldynamics.github.io/

plugins:
  - jekyll-default-layout

aux_links:
  Template Repository: https://github.com/Kareemlsd/computationaldynamics.github.io
