description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://kareemlsd.github.io/computationaldynamics.github.io/

logo: "/assets/images/TUDELFT.png"

aux_links:
  Template Repository: https://github.com/Kareemlsd/computationaldynamics.github.io
